#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

exec varnishd \
    -j unix,user=varnish \
    -F \
    -a :6081 \
    -T :6082 \
    -f /etc/varnish/default.vcl \
    -S /etc/varnish/secret \
    -s main=malloc,64M \
    -t 120 \
    -p ban_lurker_age=60.000 \
    -p ban_lurker_batch=1000 \
    -p ban_lurker_sleep=0.010 \
    -p between_bytes_timeout=60.000 \
    -p connect_timeout=3.500 \
    -p default_grace=10.000 \
    -p default_keep=0.000 \
    -p default_ttl=120.000 \
    -p fetch_chunksize=16k \
    -p first_byte_timeout=60.000 \
    -p gzip_buffer=32k \
    -p gzip_level=6 \
    -p gzip_memlevel=8 \
    -p http_gzip_support=on \
    -p http_max_hdr=128 \
    -p http_req_hdr_len=8k \
    -p http_req_size=64k \
    -p http_resp_hdr_len=8k \
    -p http_resp_size=64k \
    -p idle_send_timeout=60.000 \
    -p max_esi_depth=5 \
    -p max_restarts=4 \
    -p max_retries=4 \
    -p nuke_limit=50 \
    -p ping_interval=3 \
    -p pipe_timeout=60.000 \
    -p pool_req=10,100,10 \
    -p pool_sess=10,100,10 \
    -p prefer_ipv6=off \
    -p rush_exponent=3 \
    -p send_timeout=600 \
    -p shortlived=10.000 \
    -p tcp_keepalive_intvl=75.000 \
    -p tcp_keepalive_probes=8 \
    -p tcp_keepalive_time=7200.000 \
    -p thread_pool_add_delay=0.000 \
    -p thread_pool_destroy_delay=1.000 \
    -p thread_pool_fail_delay=0.200 \
    -p thread_pool_max=5000 \
    -p thread_pool_min=100 \
    -p thread_pool_stack=48k \
    -p thread_pool_timeout=300.000 \
    -p thread_pools=2 \
    -p thread_queue_limit=20 \
    -p timeout_idle=5.000 \
    -p timeout_linger=0.050 \
    -p vsl_buffer=4k \
    -p vsl_reclen=255b \
    -p vsl_space=80M \
    -p vsm_space=1M \
    -p workspace_backend=128k \
    -p workspace_client=128k \
    -p workspace_session=0.50k \
    -p workspace_thread=2k
